/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto_etec.view;

import java.awt.Event;
import static java.util.Collections.list;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import projeto_etec.controller.ListaController;
import projeto_etec.dao.FuncionarioDAO;
import projeto_etec.dao.ProdutoDAO;
import projeto_etec.modelo.Funcionario;
import projeto_etec.modelo.Produto;

/**
 *
 * @author Todos2
 */
public class DFrmCadLista extends javax.swing.JFrame {

    /**
     * Creates new form DFrmCadLista
     */
    public DFrmCadLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalvar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbnome = new javax.swing.JComboBox<>();
        cbprod = new javax.swing.JComboBox<>();
        txtqtd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblqtd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setResizable(false);

        btnSalvar.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel4.setText("Quantidade");

        jLabel1.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel1.setText("Nome");

        cbnome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbnome.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbnomeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbnomeKeyPressed(evt);
            }
        });

        cbprod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbprod.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbprodItemStateChanged(evt);
            }
        });
        cbprod.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbprodAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbprodActionPerformed(evt);
            }
        });
        cbprod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbprodKeyPressed(evt);
            }
        });

        txtqtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtdActionPerformed(evt);
            }
        });
        txtqtd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqtdKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel3.setText("Produto");

        lblqtd.setText("00");

        jLabel5.setFont(new java.awt.Font("Segoe Script", 0, 11)); // NOI18N
        jLabel5.setText("Quantidade Em Estoque");

        jLabel2.setFont(new java.awt.Font("Segoe Script", 0, 18)); // NOI18N
        jLabel2.setText("Cadastro de Lista");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(109, 109, 109))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtqtd)
                            .addComponent(cbprod, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbnome, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalvar)
                            .addComponent(lblqtd))
                        .addGap(94, 94, 94)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbprod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtqtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblqtd)
                    .addComponent(jLabel5))
                .addGap(23, 23, 23)
                .addComponent(btnSalvar)
                .addGap(40, 40, 40))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        ListaController lc=new ListaController();
        lc.salvar(txtqtd.getText(), cbprod.getSelectedItem().toString(), cbnome.getSelectedItem().toString());
        txtqtd.setText("");
        cbnome.requestFocus();
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void txtqtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqtdActionPerformed

    private void cbnomeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbnomeAncestorAdded
        FuncionarioDAO fdao = new FuncionarioDAO();
        List<Funcionario> funcionarios = fdao.getList();
        DefaultComboBoxModel model = 
                (DefaultComboBoxModel) cbnome.getModel();
        model.removeAllElements();
        for (Funcionario f : funcionarios){
            model.addElement(f.getNome_func());
        }
    }//GEN-LAST:event_cbnomeAncestorAdded

    private void cbprodAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbprodAncestorAdded
        Produto p1 =new Produto();
        ProdutoDAO pdao = new ProdutoDAO();
        List<Produto> produtos = pdao.getLista();
        DefaultComboBoxModel model = 
                (DefaultComboBoxModel) cbprod.getModel();
        model.removeAllElements();
        for (Produto p : produtos){
            model.addElement(p.getNome_prod());
        }
        lblqtd.setText(""+pdao.puxarQuantidadeProd(cbprod.getSelectedItem().toString()));
    }//GEN-LAST:event_cbprodAncestorAdded

    private void cbprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbprodActionPerformed
        
    }//GEN-LAST:event_cbprodActionPerformed

    private void cbprodItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbprodItemStateChanged
        try{
        ProdutoDAO pdao = new ProdutoDAO();
        lblqtd.setText(""+pdao.puxarQuantidadeProd(cbprod.getSelectedItem().toString()));
        }catch(Exception e){}
    }//GEN-LAST:event_cbprodItemStateChanged

    private void cbnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbnomeKeyPressed
        if (evt.getKeyCode() == Event.ENTER) {
            cbprod.requestFocus();
        }
    }//GEN-LAST:event_cbnomeKeyPressed

    private void cbprodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbprodKeyPressed
        if (evt.getKeyCode() == Event.ENTER) {
            txtqtd.requestFocus();
        }
    }//GEN-LAST:event_cbprodKeyPressed

    private void txtqtdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtdKeyPressed
        if (evt.getKeyCode() == Event.ENTER) {
            btnSalvarActionPerformed(null);
        }
    }//GEN-LAST:event_txtqtdKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DFrmCadLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DFrmCadLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DFrmCadLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DFrmCadLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DFrmCadLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbnome;
    private javax.swing.JComboBox<String> cbprod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblqtd;
    private javax.swing.JTextField txtqtd;
    // End of variables declaration//GEN-END:variables
}
